# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Algorithm-Combinatorics
version:      0.01
version_from: lib/Algorithm/Combinatorics.pm
installdirs:  site
requires:
    Inline::C:                     0
    Scalar::Util:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
